### Create a new notes
POST {{baseUrl}}/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRoYW5kaTExIiwiaWQiOiI2NmUzMDIzMDkwYmM0NzVjY2QwOTU1MzYiLCJpYXQiOjE3MjYyMTQwMDEsImV4cCI6MTcyNjIxNzYwMX0.Pl_UnSZ7q51-nabDd6hjU8PF7wPa9rFHLgHvU_VgwIw

{
  "content": "This note from dhandi1 and using token from middleware",
  "important": true,
  "userId": "66e3021890bc475ccd095530"
}